services:
  grok2api-rs:
    build:
      context: .
    image: ${IMAGE:-grok2api-rs:local}
    container_name: grok2api-rs
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8000}:8000"
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8000
#      RUST_LOG: ${RUST_LOG:-info}
      RUST_LOG: debug
    volumes:
      - ./data:/app/data
